##################################################################################
# Cloudify Vultr built in types and plugins definitions.
##################################################################################

plugins:
  cloudify_vultr:
    executor: central_deployment_agent
    source: cloudify_vultr

node_types:
  cloudify.vultr.nodes.Instance:
    derived_from: cloudify.nodes.Compute
    properties:
      SUBID:
        description: |
          The (existing) instance's VPS Subscription ID.
          Refer to https://api.vultr.com/v1/server/list?api_key=[api-key] for values.
        type: string
        default: {}
      OSID:
        description: |
          The instance's Operating System ID.
          Refer to https://api.vultr.com/v1/os/list for values.
        type: integer
        default: {}
      VPSPLANID:
        description: |
          The instance's VPS Subscription Plan ID.
          Refer to https://api.vultr.com/v1/plans/list for values.
        type: integer
        default: {}
      DCID:
        description: |
          The instance's Location ID.
          Refer to https://api.vultr.com/v1/regions/list for values.
        type: integer
        default: {}
      CONFIG:
        description: |
          Optional configuration parameters
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: cloudify_vultr.plugin.instance.run_instances
        stop:
          implementation: cloudify_vultr.plugin.instance.stop
